name: cta
channels:
  - conda-forge
  - defaults
dependencies:
  - alabaster=0.7.13=pyhd8ed1ab_0
  - aom=3.5.0=h7ea286d_0
  - babel=2.13.1=pyhd8ed1ab_0
  - blas=2.118=openblas
  - blas-devel=3.9.0=18_osxarm64_openblas
  - blosc=1.21.3=h313beb8_0
  - bottleneck=1.3.5=py38heec5a64_0
  - brotli=1.0.9=h1a28f6b_7
  - brotli-bin=1.0.9=h1a28f6b_7
  - brotli-python=1.0.9=py38h6f2b01f_5
  - brunsli=0.1=h9f76cd9_0
  - bzip2=1.0.8=h3422bc3_4
  - c-ares=1.20.1=h93a5062_0
  - ca-certificates=2023.7.22=hf0a4a13_0
  - cairo=1.16.0=h29d4eff_2
  - certifi=2023.7.22=pyhd8ed1ab_0
  - cffi=1.15.1=py38h80987f9_3
  - cfitsio=3.470=ha83d327_7
  - cftime=1.6.2=py38hb08c31d_0
  - charls=2.2.0=hc377ac9_0
  - charset-normalizer=3.3.1=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - cycler=0.12.1=pyhd8ed1ab_0
  - dav1d=1.2.1=hb547adb_0
  - deepxde=1.9.3=pyhd5b0024_0
  - docutils=0.18.1=py38hca03da5_3
  - dxchange=0.1.8=pyhd8ed1ab_0
  - dxfile=0.5=py_1
  - edffile=5.0.0=pyh24bf2e0_1000
  - eigen=3.4.0=hc021e02_0
  - ffmpeg=4.2.2=h04105a8_0
  - filelock=3.9.0=py38hca03da5_0
  - fontconfig=2.13.94=heb65262_0
  - freetype=2.10.4=h17b34a0_1
  - gettext=0.21.1=h0186832_0
  - giflib=5.2.1=h1a8c8d9_3
  - glib=2.69.1=h514c7bf_2
  - gmp=6.2.1=h9f76cd9_0
  - gmpy2=2.1.2=py38h8c48613_0
  - gnutls=3.6.15=h887c41c_0
  - graphite2=1.3.14=hc377ac9_1
  - gst-plugins-base=1.14.1=h313beb8_1
  - gstreamer=1.14.1=h80987f9_1
  - h5py=3.9.0=py38haafd478_0
  - harfbuzz=4.3.0=he9eebac_1
  - hdf4=4.2.13=h5e329fb_3
  - hdf5=1.12.1=h05c076b_3
  - icu=68.2=hbdafb3b_0
  - idna=3.4=pyhd8ed1ab_0
  - imagecodecs=2023.1.23=py38h604db08_0
  - imagesize=1.4.1=pyhd8ed1ab_0
  - importlib-metadata=6.8.0=pyha770c72_0
  - jinja2=3.1.2=py38hca03da5_0
  - joblib=1.3.2=pyhd8ed1ab_0
  - jpeg=9e=h1a8c8d9_3
  - jxrlib=1.1=h27ca646_2
  - kiwisolver=1.4.4=py38h313beb8_0
  - krb5=1.20.1=h69eda48_0
  - lame=3.100=h1a8c8d9_1003
  - lcms2=2.15=h481adae_0
  - lerc=3.0=hc377ac9_0
  - libaec=1.0.4=hc377ac9_1
  - libavif=0.11.1=h9f83d30_2
  - libblas=3.9.0=18_osxarm64_openblas
  - libbrotlicommon=1.0.9=h1a28f6b_7
  - libbrotlidec=1.0.9=h1a28f6b_7
  - libbrotlienc=1.0.9=h1a28f6b_7
  - libcblas=3.9.0=18_osxarm64_openblas
  - libclang=12.0.0=default_hc321e17_4
  - libcurl=8.4.0=h3e2b118_0
  - libcxx=14.0.6=h848a8c0_0
  - libdeflate=1.17=h80987f9_1
  - libedit=3.1.20191231=hc8eb9b7_2
  - libev=4.33=h642e427_1
  - libffi=3.4.4=hca03da5_0
  - libgfortran=5.0.0=13_2_0_hd922786_1
  - libgfortran5=13.2.0=hf226fd6_1
  - libiconv=1.17=he4db4b2_0
  - libidn2=2.3.4=h1a8c8d9_0
  - liblapack=3.9.0=18_osxarm64_openblas
  - liblapacke=3.9.0=18_osxarm64_openblas
  - libllvm12=12.0.1=h93073aa_2
  - libnetcdf=4.8.1=h0fce390_4
  - libnghttp2=1.57.0=h62f6fdd_0
  - libopenblas=0.3.24=openmp_hd76b1f2_0
  - libopus=1.3.1=h27ca646_1
  - libpng=1.6.39=h80987f9_0
  - libpq=12.15=h02f6b3c_1
  - libprotobuf=3.20.3=h514c7bf_0
  - libssh2=1.10.0=h02f6b3c_2
  - libtasn1=4.19.0=h1a8c8d9_0
  - libtiff=4.5.1=h313beb8_0
  - libunistring=0.9.10=h3422bc3_0
  - libuv=1.44.2=h80987f9_0
  - libvpx=1.10.0=hc377ac9_0
  - libwebp=1.3.2=ha3663a8_0
  - libwebp-base=1.3.2=hb547adb_0
  - libxml2=2.10.4=h372ba2a_0
  - libxslt=1.1.37=h1bd8bc4_0
  - libzip=1.8.0=h62fee54_1
  - libzopfli=1.0.3=h9f76cd9_0
  - llvm-openmp=17.0.2=h1c12783_0
  - lz4-c=1.9.4=hb7217d7_0
  - markupsafe=2.1.1=py38h1a28f6b_0
  - matplotlib-base=3.4.3=py38hb140015_1
  - mpc=1.1.0=h8c48613_1
  - mpfr=4.0.2=h695f6f0_1
  - mpmath=1.3.0=py38hca03da5_0
  - ncurses=6.4=h313beb8_0
  - netcdf4=1.6.2=py38h053bab8_0
  - nettle=3.7.3=h84b5d62_1
  - networkx=3.1=py38hca03da5_0
  - ninja=1.10.2=hca03da5_5
  - ninja-base=1.10.2=h525c30c_5
  - nspr=4.35=hb7217d7_0
  - nss=3.89.1=h313beb8_0
  - numexpr=2.8.4=py38h79ee842_1
  - numpy=1.24.3=py38h1398885_0
  - numpy-base=1.24.3=py38h90707a3_0
  - openblas=0.3.24=openmp_hce3e5ba_0
  - opencv=4.6.0=py38hc90a7da_5
  - openh264=1.8.0=h98b2900_0
  - openjpeg=2.3.0=h7a6adac_2
  - openssl=3.1.4=h0d3ecfb_0
  - packaging=23.2=pyhd8ed1ab_0
  - pandas=1.5.3=py38h78102c4_0
  - pcre=8.45=hbdafb3b_0
  - pillow=9.4.0=py38h313beb8_1
  - pip=23.2.1=py38hca03da5_0
  - pixman=0.40.0=h1a28f6b_0
  - pyaml=23.9.7=pyhd8ed1ab_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyevtk=1.6.0=pyha21a80b_0
  - pygments=2.16.1=pyhd8ed1ab_0
  - pyparsing=3.1.1=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.8.18=hb885b13_0
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.8=2_cp38
  - pytorch=2.0.1=gpu_mps_py38h20d1048_0
  - pytz=2023.3.post1=pyhd8ed1ab_0
  - pyyaml=5.4.1=py38hea4295b_1
  - qt-main=5.15.2=ha2d02b5_7
  - qt-webengine=5.15.9=h2903aaf_7
  - qtwebkit=5.212=h19f419d_5
  - readline=8.2=h1a28f6b_0
  - requests=2.31.0=pyhd8ed1ab_0
  - scikit-learn=1.3.0=py38h46d7db6_0
  - scikit-optimize=0.9.0=pyhd8ed1ab_1
  - scipy=1.9.3=py38h9d039d2_2
  - setuptools=68.0.0=py38hca03da5_0
  - six=1.16.0=pyh6c4a22f_0
  - sleef=3.5.1=h80987f9_2
  - snappy=1.1.10=h17c5cce_0
  - snowballstemmer=2.2.0=pyhd8ed1ab_0
  - spefile=1.6.1=pyhd3deb0d_0
  - sphinx=7.0.0=pyhd8ed1ab_0
  - sphinxcontrib-applehelp=1.0.2=pyhd3eb1b0_0
  - sphinxcontrib-devhelp=1.0.2=pyhd3eb1b0_0
  - sphinxcontrib-htmlhelp=2.0.0=pyhd3eb1b0_0
  - sphinxcontrib-jsmath=1.0.1=pyhd8ed1ab_0
  - sphinxcontrib-qthelp=1.0.3=pyhd3eb1b0_0
  - sphinxcontrib-serializinghtml=1.1.5=pyhd3eb1b0_0
  - sqlite=3.41.2=h80987f9_0
  - sympy=1.11.1=py38hca03da5_0
  - threadpoolctl=3.2.0=pyha21a80b_0
  - tifffile=2023.4.12=pyhd8ed1ab_0
  - tk=8.6.12=hb8d0fd4_0
  - tornado=6.1=py38hea4295b_1
  - typing-extensions=4.7.1=py38hca03da5_0
  - typing_extensions=4.7.1=py38hca03da5_0
  - urllib3=2.0.7=pyhd8ed1ab_0
  - wheel=0.41.2=py38hca03da5_0
  - x264=1!152.20180806=h1a28f6b_0
  - xz=5.4.2=h80987f9_0
  - yaml=0.2.5=h3422bc3_2
  - zfp=1.0.0=hb6e4faa_3
  - zipp=3.17.0=pyhd8ed1ab_0
  - zlib=1.2.13=h5a0b063_0
  - zstd=1.5.5=hd90d995_0
prefix: /opt/homebrew/Caskroom/miniconda/base/envs/cta
